/// Flutter icons SgIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SgIcons
///      fonts:
///       - asset: fonts/SgIcons.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class SgIcons {
  SgIcons._();

  static const _kFontFam = 'SgIcons';

  static const IconData home = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData house = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData heath = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData stethoscope = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData pill = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData people = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData exit = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData news = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData sg50 = const IconData(0xe808, fontFamily: _kFontFam);
}
